[package]
name = "dns_decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns_types = { path = "../dns_types" }
nom = "7.1.3"
hex = "0.4.3"
thiserror = "1.0.56"
