[package]
name = "dns_encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns_types = { path = "../dns_types" }
hex = "0.4.3"
bitvec = "1.0.1"
